### ISSUE TITLE
Simple query taking 12 seconds

### ISSUE THREAD

**Issue by zero-master** [googleapis/java-datastore#209]
```
public List<Campaign3> getLiveCampaignsForAccount(Long accountId) {
        EntityQueryRequest request = datastoreAdapter.getEm().createEntityQueryRequest("SELECT * FROM " + ENTITY_NAME + " WHERE accountId=@1 and live = @2");
        request.addPositionalBinding(accountId);
        request.addPositionalBinding(true);
        QueryResponse<Campaign3> response = datastoreAdapter.getEm().executeEntityQueryRequest(Campaign3.class, request);
        return response.getResults();

```

**Comment by BenWhitehead** [comment]
Can you provide some details regarding what environment you're running in to help us narrow down the problem space?

1. Which version of java?
2. Which version of google-cloud-datastore?
3. Where is your code running?
  * GCE, App Engine, Cloud Run, etc?
  * What region is your code running in? ([GCP Locations](https://cloud.google.com/compute/docs/regions-zones#locations)
  * What region is your Datastore database located?
  * What OS is your code running on?
4. Do you have a sense of the magnitude of the number of entities in your database? 100k, 1m, 10m etc?

**Comment by zero-master** [comment]
1. java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

2.   <artifactId>google-cloud-datastore</artifactId>
            <version>1.0.1</version>

3. GCE

Database location: nam5 (us-central)

Code running in: GCE (us-east1-d)

> uname -a
> 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux

4. 

Database stats:

Entities
179778 
329.69 MB
Built-in Indexes 
7088450
736.96 MB
Composite Indexes 
539327
46.24 MB
Total Size
1.09 GB

**Comment by BenWhitehead** [comment]
You may try updating your version of google-cloud-datastore to the latest version (`1.104.0`), version 1.0.1 is more than 4 years old at this point, and there have been many fixes in the meantime.

If updating doesn't seem to improve things, the next things I'd look into are:
1. Do you have a [composite index](https://cloud.google.com/datastore/docs/concepts/indexes#index_definition_and_structure) created for for `accountId` and `live` to ensure you're not running into any merge-join slowness
2. Try to keep a count of the number of records being returned by your query. Datastore is only able to return 300 results per page of the response, and has to send another request to get the next page.
3. Try enabling some RPC logging to see if we can get some more timing details by doing the following
    1. Create a file, `logging.properties` with the following contents
        ```
        handlers=java.util.logging.ConsoleHandler
        .level=INFO

        java.util.logging.ConsoleHandler.level=ALL
        java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter

        # headers + proxy resolution information
        sun.net.www.protocol.http.level=FINEST
        ```
    2. Then when running their program add a java system property to their command to point to the properties file
      * `-Djava.util.logging.config.file=path/to/logging.properties`
    3. Observe request logging on stdout
