### ISSUE TITLE
Datastore emulator fails to start without project id property

### ISSUE THREAD

**Issue by artemptushkin** [googleapis/java-datastore#355]
#### Environment details

1. GCloud datastore emulator 2.1.0
2. Google Cloud SDK 327.0.0
2. OS type and version: NAME="Ubuntu" VERSION="18.04.4 LTS (Bionic Beaver)"  / MacOS Catalina 10.15.7 (19H15)
3. Java version: OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10) / OpenJDK Runtime Environment (build 11.0.7+10)
4. Libs:
* https://github.com/GoogleCloudPlatform/spring-cloud-gcp: `org.springframework.cloud:spring-cloud-gcp-starter-data-datastore:1.2.5.RELEASE`, I checked - same with the latest
* `google-cloud-datastore:1.104.0`
* `google-cloud-core:1.93.7`

#### Steps to reproduce
This version emulator fails to start without `--project` property

  1. `gcloud beta emulators datastore start`

```sh
ERROR: (gcloud.beta.emulators.datastore.start) The required property [project] is not currently set.
You may set it for your current workspace by running:

  $ gcloud config set project VALUE

or it can be set temporarily by the environment variable [CLOUDSDK_CORE_PROJECT]
```

Starting emulator with Java code like this:

```java
LocalDatastoreHelper.create(settings.getConsistency(), settings.getPort());
```

Causes: no messages in logs, the application failed to call the Datastore then with I/O exceptions, i.e. curl doesn't work.

### Workaround

Set env variable: `CLOUDSDK_CORE_PROJECT` with the projectId value

### Questions

1. Why `LocalDatastoreHelper` doesn't pass `--project` on startup and doesn't expect this from the builder?
2. Shouldn't `LocalDatastoreHelper #start` fail to start on this kind of errors?

Besides the outcomes of these questions, I would expect this class to fail to start or log something.

**Comment by meredithslota** [comment]
I wonder if this is an issue with out-dated documentation — https://cloud.google.com/sdk/gcloud/reference/beta/emulators/datastore/start also declares that the`--project` flag isn't required, but maybe it is now. Are you setting the variables re: the `env-init` command? It seems like it's expecting a variable like this: DATASTORE_PROJECT_ID=my-project-id (as per this page: https://cloud.google.com/datastore/docs/tools/datastore-emulator#automatically_setting_the_variables).

**Comment by artemptushkin** [comment]
@meredithslota I question here particularly `LocalDatastoreHelper` class and troubleshooting on its start-up issues.

Consider it starts in an isolated environment without any env variable predefined, then `LocalDatastoreHelper starts` finishes but the method caller never knows that it failed to start due to missing an env variable, there is no log message.

As well there is no method in builder to pass the project id explicitly
![image](https://user-images.githubusercontent.com/22632802/141960754-5c13d1a2-aace-4593-99cc-89c62fddb8a4.png)

I propose:
* add a method to the builder to pass the project id (if project id is optional it's still good to let you class consumers to pass its value)
* log when it fails to start due to missing env variable with a reasoning message

It will make it clear as right now there is no clue to know _why_ it failed to start when no env variable has been provided.

**Comment by meredithslota** [comment]
There's a similar issue with the `LocalDatastoreHelper` #302 — @prash-mi can you include this with your investigation of the other issue?

**Comment by jainsahab** [comment]
@artemptushkin , Thanks for reporting this.

We have fixed this issue in [this PR](https://github.com/googleapis/java-datastore/pull/923) and is up for review. You can find the explanation and fix in the PR itself.
