### ISSUE TITLE
Transaction doesn't update entity

### ISSUE THREAD

**Issue by aaukhatov** [googleapis/java-datastore#554]
I use your cloud functions to react some event in topic.
When even has occurred function has to select an entity to change a state.
But it doesn't work. The library doesn't update en entity in Datastore.

#### Environment details

1. GCP Cloud Function

#### Steps to reproduce

  1. Create a cloud function
  2. Add a dependency to work with Datastore (v2.1.2)
  3. Prepare some entities
  4. The function has to select some entities by query
  5. Then update it

#### Code example

```java
Datastore datastore = DatastoreOptions.getDefaultInstance().getService()

Query<Entity> query = Query.newEntityQueryBuilder()
                    .setKind("MyEntity")
                    .setFilter(eq("phoneNumber", "+15551014397"))
                    .build();

QueryResults<Entity> results = datastore.run(query);

Entity entity = results.next();

Transaction transaction = datastore.newTransaction();

Entity updatedEntity = Entity.newBuilder(entity)
        .set("state", 3)
        .build();

transaction.update(updatedEntity);

transaction.commit();
```

#### Stack trace
The result is success. No error.
But the entity in Datastore has not been updated with field entity.state = 3 - there is previous value/

**Comment by jainsahab** [comment]
Hi @aaukhatov , i tried replicating this issue with the mentioned library version as well as within a cloud function but **couldn't replicate it**.  Are you still facing this issue? If yes, would you be able to provide a dummy code sample where this issue is reproducible?

Thanks,

**Comment by aaukhatov** [comment]
> Hi @aaukhatov , i tried replicating this issue with the mentioned library version as well as within a cloud function but **couldn't reproduce it**. Are you still facing this issue? If yes, would you be able to provide a dummy code sample where this issue is reproducible?
> 
> Thanks,

Hi @jainsahab we just stopped using Datastore.
