### ISSUE TITLE
Monorepo style suggested changes

### ISSUE THREAD

**Issue by Capstan** [googleapis/java-datastore#590]
Internally to Google, clshepherd / clrobot suggest changes to apply best practices. It made the following suggestions:

> Fix 2 ErrorProneStyle findings:
> * Constructors and methods with the same name should appear sequentially with no other code in between. Please re-order or re-name methods.
> * This catch block catches an exception and re-throws another, but swallows the caught exception rather than setting it as a cause. This can make debugging harder.

I'm not sure these are all available via the public errorprone module, but perhaps some would get caught upstream if it were installed per https://errorprone.info/docs/installation#maven.

**Comment by Capstan** [comment]
Found the external link for the latter: https://errorprone.info/bugpattern/UnusedException

**Comment by meredithslota** [comment]
@Capstan This looks largely addressed by https://github.com/googleapis/java-datastore/pull/592 which has been merged. Were there remaining items you wanted here or is this ok to close out?

**Comment by Capstan** [comment]
Ah, I think the hope was that #592 would be part #1, and then someone would select the interesting things to fix, and then fix them. This first PR was just an ad hoc addressing of a couple changes that got suggested internally. That said, if you want to drop this in favor of a more holistic approach, I'm fine with that. (Or accept it and deal with the others later, also fine.)

Until such time as these are changed to errors, though, this will just be noise that might slip through code review.

**Comment by meredithslota** [comment]
I'm wondering if this is something that we should consider for all Java repos, honestly. It's a larger question.
