### ISSUE TITLE
datastore.Query#newGqlQueryBuilder: Gql query with HAS ANCESTOR key fails when combined with setBinding

### ISSUE THREAD

**Issue by zhumin8** [googleapis/java-datastore#627]
Hi, I am trying to reproduce a reported issue in Spring Cloud GCP and came across this error.

When I do a GQL query with HAS ANCESTOR key via datastore client library, if I set binding at the same time, it is getting below error. The same query works fine with plain string gql query.

I wonder if this is a bug or intentionally unsupported? To what extent is Gql query supported in datastore client library?

I couldn’t find more documentation about this other than the Javadoc, so please point me to if this is already addressed.

Error:
```
com.google.cloud.datastore.DatastoreException: Encountered "@id" at line 1, column 62.
Was expecting one of:
    <INTEGER> ...
    <SINGLE_QUOTE_STRING> ...
    <DOUBLE_QUOTE_STRING> ...
```
Data to reproduce:
I have entities “books” and “chapters”, some chapters have book(id = “id4”) as ancestor. Below GQL query results in error.

```
// this one result in error
Query<Entity> query =
   Query.newGqlQueryBuilder(Query.ResultType.ENTITY,
           "SELECT * from chapters WHERE __key__ HAS ANCESTOR KEY(books, @id)")
       .setBinding("id", "id4")
       .setAllowLiteral(true).build();
```
Also run below queries to verify plain gql query with no binding works, and a simpler gql with query also works fine.
```
// this one works fine
Query<Entity> query =
   Query.newGqlQueryBuilder(Query.ResultType.ENTITY,
           "SELECT * from chapters WHERE __key__ HAS ANCESTOR KEY(books, 'id4')")
       .setAllowLiteral(true).build();


// this one also works fine
Query<Entity> query =
   Query.newGqlQueryBuilder(Query.ResultType.ENTITY,
           "SELECT * from chapters WHERE page = @page")
       .setBinding("page", 12)
       .setAllowLiteral(true).build();
```

#### version info

google-cloud-datastore-2.2.2

**Comment by kolea2** [comment]
Hi @zhumin8, thanks so much for the detailed report and reproducible issue. I am still investigating this, but I wanted to share a possible workaround with you:

I was able to get queries working by replacing the entire `KEY(books, @id)` section with a key binding. For example:
```
Query<Entity> query =
   Query.newGqlQueryBuilder(Query.ResultType.ENTITY,
           "SELECT * from chapters WHERE __key__ HAS ANCESTOR @key")
               .setBinding("key", KEY_VARIABLE)
               .setAllowLiteral(true)
               .build();
```

I will keep this thread updated with additional findings.

**Comment by kolea2** [comment]
Took a look at the [GQL Grammar](https://cloud.google.com/datastore/docs/reference/gql_reference#grammar), `<key-path-element>`s can only accept string literals or integer literals. Therefore, this error is expected - you can bind a key object instead as shown above.
