### ISSUE TITLE
Add unit tests for Query classes

### ISSUE THREAD

**Issue by ajkannan** [googleapis/java-datastore#732]
For example, the builders for `StructuredQuery` don't seem to be tested.

**Comment by meredithslota** [comment]
Moved to java-datastore repo. Backlog link is no longer functional, and I'm not entirely sure if this work still needs to be done, but it wasn't getting looked at in the older mono repo. So, we'll see!

**Comment by kolea2** [comment]
For all classes that extend `Query`, there appears to be coverage in https://github.com/googleapis/java-datastore/blob/main/google-cloud-datastore/src/test/java/com/google/cloud/datastore/StructuredQueryTest.java, so it looks like at some point this was addressed. Closing this out.
