### ISSUE TITLE
Chore: Use `GsonFactory` as `JsonFactory` implementation

### ISSUE THREAD

**Issue by Capstan** [googleapis/java-datastore#779]
For a variety of reasons, mostly to do with historical security issues, the monorepo and Google security prefers Gson to Jackson, and thus `GsonFactory` to `JacksonFactory`. Pushing this change upstream in lieu of patching the monorepo import.

**Comment by meredithslota** [comment]
(Related internal issue for maintainers b/216657461 for a different library, for additional context.)
